//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioHIS.WS_HIS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="WS_HIS.BiomedServices")]
    public interface BiomedServices {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServicioHIS.WS_HIS.proccessRequestResponse proccessRequest(ServicioHIS.WS_HIS.proccessRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioHIS.WS_HIS.proccessRequestResponse> proccessRequestAsync(ServicioHIS.WS_HIS.proccessRequestRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class serviceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="proccessRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class proccessRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string data;
        
        public proccessRequestRequest() {
        }
        
        public proccessRequestRequest(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="proccessRequestResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class proccessRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServicioHIS.WS_HIS.serviceResponse @return;
        
        public proccessRequestResponse() {
        }
        
        public proccessRequestResponse(ServicioHIS.WS_HIS.serviceResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BiomedServicesChannel : ServicioHIS.WS_HIS.BiomedServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BiomedServicesClient : System.ServiceModel.ClientBase<ServicioHIS.WS_HIS.BiomedServices>, ServicioHIS.WS_HIS.BiomedServices {
        
        public BiomedServicesClient() {
        }
        
        public BiomedServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BiomedServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiomedServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiomedServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioHIS.WS_HIS.proccessRequestResponse ServicioHIS.WS_HIS.BiomedServices.proccessRequest(ServicioHIS.WS_HIS.proccessRequestRequest request) {
            return base.Channel.proccessRequest(request);
        }
        
        public ServicioHIS.WS_HIS.serviceResponse proccessRequest(string data) {
            ServicioHIS.WS_HIS.proccessRequestRequest inValue = new ServicioHIS.WS_HIS.proccessRequestRequest();
            inValue.data = data;
            ServicioHIS.WS_HIS.proccessRequestResponse retVal = ((ServicioHIS.WS_HIS.BiomedServices)(this)).proccessRequest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioHIS.WS_HIS.proccessRequestResponse> ServicioHIS.WS_HIS.BiomedServices.proccessRequestAsync(ServicioHIS.WS_HIS.proccessRequestRequest request) {
            return base.Channel.proccessRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioHIS.WS_HIS.proccessRequestResponse> proccessRequestAsync(string data) {
            ServicioHIS.WS_HIS.proccessRequestRequest inValue = new ServicioHIS.WS_HIS.proccessRequestRequest();
            inValue.data = data;
            return ((ServicioHIS.WS_HIS.BiomedServices)(this)).proccessRequestAsync(inValue);
        }
    }
}
